### ISSUE TITLE
Can't use Super key

### ISSUE THREAD

**Issue by 4708696-UniGe** [Leleat/Quick-App-Launcher#1]
Seems i can't use Super key to set shortcut, it doesn't take the input

Gnome 40 on Fedora 34

**Comment by Leleat** [comment]
> Seems i can't use Super key to set shortcut, it doesn't take the input

Just to be sure, do you mean just the `Super` key or the `Super` + `Some other key`? I am also on Fedora and it works for me. Can you set shortcuts with `Super` in Gnome settings page?

**Comment by 4708696-UniGe** [comment]
I mean Super + Some other key, sorry if i don't specified it.
Yes i can set it in gnome settings, i want to use this extension because i can't find terminal command to launch android studio so this extension work perfect for me but i'd like to use Super key

**Comment by Leleat** [comment]
Weid, don't know what could the be the cause...

Tbh I am also no longer maintaining this extension, so I won't be looking into it, sorry. Reason is that I've found https://extensions.gnome.org/extension/1336/run-or-raise/ which does the same but also offer more options.

**Comment by 4708696-UniGe** [comment]
thanks, now i'll give it a try
